---
deployment:
 tasks:
 - export DEPLOYPATH=/home/lq4iv36g9c1r/public_html/another.comoleermicartaastral.com
 - /bin/cp ./public $DEPLOYPATH
 - /bin/chmod 755 ${DEPLOYPATH}
 - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 '{}' \;
 - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 '{}' \;